### ISSUE TITLE
Lucian and his addons...

### ISSUE THREAD

**Issue by kchamp64** [Muse30/PortAIO#11]
I recently bought Lucian, since I had been playing him a while, to test him and the Port AIO addons for him. Overall the experience was not pleasant and all 3 scripts were a disappointment in my opinion. LCS Lucian was sluggish with the combo, and often completely refused to dash in and begin weaving. There was also no option on who the semi-auto ult would hit, and the pre built logic really didn't do the greatest job at it. None of the scripts also had an auto follow option, which I believe is one of the most important and unique characteristics for a good lucian script. iLucian also didn't combo well and disabled the ult altogether, even with block manual R on off. I hope you can look into his scripts and try to find a solution or do another Dual Port if that proves too difficult. Thanks for all your hard work in continuing Berb's legacy. Keep Port AIO Great.

**Comment by Muse30** [comment]
yeah I main lucian and I feel you.. probably will try to fix lucian or port a new one we will see
