### ISSUE TITLE
f5 crash 

### ISSUE THREAD

**Issue by KiriharaSenpai** [Muse30/PortAIO#12]
hey buddy thanks for your hardworks can you check out render settings whenever i press f5 it crashes

**Comment by Muse30** [comment]
console error?

**Comment by spvrtan** [comment]
does the same thing for me too

**Comment by Muse30** [comment]
update common and try again https://github.com/Muse30/Berb.Common

**Comment by KiriharaSenpai** [comment]
gimme 5 second gonna upload it

**Comment by KiriharaSenpai** [comment]
i already trıed twıce

**Comment by KiriharaSenpai** [comment]
fixed thank u so much

**Comment by Muse30** [comment]
no problem
