### ISSUE TITLE
Request: Please add EB "Simple Vayne" to this awesome AIO

### ISSUE THREAD

**Issue by lightduy94** [Muse30/PortAIO#18]
As i see that all 2 vayne addons in this AIO not working good as it should. And i found that EB have 2 working good Vayne addons is "Auto Carry Vayne" and "Simple Vayne" but i prefer Simple Vayne because it give user more customizeable.
Please add it to this AIO because i always have to Enabled Ulti mode when i play Vayne and F5 every game!

**Comment by Xelamats** [comment]
This is PortAIO. That means that addons from EB should and will not be added into this. If you wish to use a EB addon, simply go into the core of PortAIO (ingame) and tick Utility only and F5. That will make it so PortAIO only loads the utilities and not a champion script.
