### ISSUE TITLE
Lee Crash

### ISSUE THREAD

**Issue by dankmemer420** [Muse30/PortAIO#2]
#1 priority should be fixing the lee crash in valralve sharp since it crashes whenever you q basically. Thanks for continuing Berbs project.

**Comment by IlikeBaconLol** [comment]
I already told u dankmeme.... Clear ur apdata

**Comment by IlikeBaconLol** [comment]
Ty to keep up the project

**Comment by Muse30** [comment]
wait so not anyone has this problem?

**Comment by IlikeBaconLol** [comment]
No he only needs to clear apdata

**Comment by IlikeBaconLol** [comment]
And if he wants to keep his addon he has to open eb delete apdata and on the opened eb udapte all addons, close rb reopen it and udapte all addons, its a fix for all pirtaio bugs dues to apdata

**Comment by dankmemer420** [comment]
I've cleared my appdata multiple times rofl.

**Comment by IlikeBaconLol** [comment]
Excuse me so, brian is working on the fix

**Comment by Muse30** [comment]
oh so that happens on the original too.. lets wait for him to fix it

**Comment by dankmemer420** [comment]
Doesnt crash when i use bansharp valralve just portaio and theres no reports of lee causing crashes on the thread.

**Comment by Muse30** [comment]
hmm ok I will check myself then

**Comment by dankmemer420** [comment]
Cheers man.

**Comment by IlikeBaconLol** [comment]
Thiq bug happened to me on bansharp to and reported to brian so...

**Comment by IlikeBaconLol** [comment]
I think maybe some conflicts ? Try to uninstal some addon disable all utilities

**Comment by dankmemer420** [comment]
Did last game.

**Comment by Hidan123** [comment]
This bug is only in normal/ranked game btw

**Comment by dankmemer420** [comment]
Dunno if berb updated but imsosharp updated valralve https://github.com/myo/LeagueSharp-2/tree/master/Valvrave%20Sharp

**Comment by Muse30** [comment]
2 days ago.. he might of but I will check

**Comment by berbb** [comment]
I did, but not a single impact on fixing the Q crash.

**Comment by dankmemer420** [comment]
ah rip @berbb
