### ISSUE TITLE
ElRyze Do not use the skills LaneClear

### ISSUE THREAD

**Issue by lyn690697457** [Muse30/PortAIO#23]
No matter how I set that he still does not use the skills LaneClear

**Comment by Muse30** [comment]
let me check.. do you use any humanizeRs?

**Comment by lyn690697457** [comment]
did not use

**Comment by lyn690697457** [comment]
JungleClear ，The same situation does not use the skills

**Comment by Muse30** [comment]
fixed m8.. report back plz

**Comment by lyn690697457** [comment]
OK

**Comment by lyn690697457** [comment]
Work，JungleClear and LaneClear

**Comment by lyn690697457** [comment]
no problem
