### ISSUE TITLE
Yasuo Valvresharp bug

### ISSUE THREAD

**Issue by lightduy94** [Muse30/PortAIO#24]
I checked Q while gapcloser in combo mode but it still doesn't use it. Also it wasted Q3 knockup on minions in combo.
E to lasthit in laneclear mode not working too!
Please fix it. Thank you! Not lie, really really thank you for all the things you're doing!

**Comment by Muse30** [comment]
I'll check but looks like the original yasuo from bansharp is having errors too

**Comment by lightduy94** [comment]
@Muse30 just tested it again and found that Valvre Evade is not working too! I can't find menu to choose what skill will be dodged.

**Comment by beadwarf** [comment]
Sometimes at combo Q3 goes nowhere

**Comment by Muse30** [comment]
same error in original vlavresharp .. pls lets just wait untill the original is fixed
