### ISSUE TITLE
If you have time to consider the following script port

### ISSUE THREAD

**Issue by lyn690697457** [Muse30/PortAIO#26]
Evade# https://github.com/Esk0r/LeagueSharp/tree/master/Evade
AutoLeveler https://github.com/tr33s/LeagueSharp/tree/master/AutoLeveler
Not have to port them, just to let you consider the following. I do not want to put you to increase the pressure of work。Thank you for your project

**Comment by Muse30** [comment]
the auto leveler is in the to-do list
about Evade# I already done it but it has a lot of errors so probably not
