### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Pentarina** [Muse30/PortAIO#28]
http://prnt.sc/b5955w
http://prnt.sc/b595cp
Fix plz.

**Comment by Muse30** [comment]
fixed sorry about that

**Comment by Muse30** [comment]
o wait is with berb.common

do you still have the error?

**Comment by Pentarina** [comment]
I've updated elobuddy to 9.10. Still same errors, only ezevade, ElRengarRevamped, Hoola Master Yi, Kalista Airlines, Nechrito Rengar And Seph Kha'zix working fine.
