### ISSUE TITLE
Twisted Fate

### ISSUE THREAD

**Issue by spvrtan** [Muse30/PortAIO#3]
tends to q at allies gapclosers/or to mouse position, fix please buddy :)

**Comment by Muse30** [comment]
Tf doesnt have anti gapcloser tho.. I will check either way

**Comment by spvrtan** [comment]
i know, but its still doing it, ty :)

**Comment by Muse30** [comment]
well I will have to jump in to a game myself to test this because in the code there is nothing about cursor position or gapclosers

**Comment by voidsurfer** [comment]
I don't understand this issue, How can TF even Anti-Gapclose to Mouse Cursor? What ability would that be?

The only Anti-Gapcloser he has is Pick A Card->Yellow Card->Targetet, so it would be impossible to cast to cursor.

Also there is a huge bug in EB with Gapclosers in general where allies trigger the gapcloser in the eb.core. Happens on native EB scripts aswell as ports. I.E: Ahri tries to charm allied quinn when ulti, Ahri tries to charm allied graves when dashing.

**Comment by spvrtan** [comment]
Let me put it simpler, TF will Q to allied gapclosers, for example one game i was in, our khazix was using his E and it would q towards him. Makes it extremely annoying in teamfights when allies have gapclosers and it Q's them instead of the enemy. Also it will randomly Q towards cursor position in teamfights.

**Comment by wwomegaww** [comment]
Just like spvrtan said, also it happen with anothers champs like teemo putting mushrooms when an allied use some jump

**Comment by voidsurfer** [comment]
Quoting myself here:
Also there is a huge bug in EB with Gapclosers in general where allies trigger the gapcloser in the eb.core. Happens on native EB scripts aswell as ports. I.E: Ahri tries to charm allied quinn when ulti, Ahri tries to charm allied graves when dashing.

**Comment by Muse30** [comment]
guys the OnGapCloser Event is not even triggered in this TF so idk what are you guys talking about

anyways I cant reproduce this right now so I might just port another TF

**Comment by spvrtan** [comment]
I guess it's EB's problem and not the script then
