### ISSUE TITLE
Kog maw doesnt use E in harass and combo mode

### ISSUE THREAD

**Issue by DannyTheGod** [Muse30/PortAIO#31]
i tried 3 addon , OKTW and Sharpshooter dont use E , Challenger uses it but if enemy in AA range, sorry for my bad English , English isnt my first language
and another poblem , idk how to say but here 
http://i.imgur.com/HpXbIU7.png
http://i.imgur.com/MJGPU3X.png

**Comment by lgndz** [comment]
As for pics above,

The "W" menu config is for the "E" spell and vice-versa

What Prediction were you using for OKTW? Ive had problems with SPRED

**Comment by Muse30** [comment]
I will check

**Comment by Muse30** [comment]
fixed
