### ISSUE TITLE
Still install failed

### ISSUE THREAD

**Issue by Pentarina** [Muse30/PortAIO#33]
I can't still install this. What i'm doing wrong?
http://prnt.sc/b5icz3
http://prnt.sc/b5idct
btw. EzEvade working fantastic. Great work!

**Comment by Muse30** [comment]
Do you have the common installed?

**Comment by Pentarina** [comment]
Berb Common? Nope.
I tried but all the times "failed to install".

**Comment by Muse30** [comment]
https://github.com/Muse30/Berb.Common

Can you install that?

**Comment by Pentarina** [comment]
http://prnt.sc/b5il14 
As you can see.

**Comment by Muse30** [comment]
No idea... Maybe try to clear your appdata, delete the EB folder there

**Comment by Pentarina** [comment]
http://prnt.sc/b5inbt
Still same error ;//

**Comment by Pentarina** [comment]
[05/18/2016 15:40:12] <Error> Failed to install addon: "https://github.com/Muse30/Berb.Common+Berb.Common.csproj". Addon state: "CompilingError". The addon either did not update or did not compile!

**Comment by Muse30** [comment]
Go to your en folder/logs and show me the log file

**Comment by Pentarina** [comment]
^

**Comment by Pentarina** [comment]
[05/18/2016 15:40:12] Failed to install addon: "https://github.com/Muse30/Berb.Common+Berb.Common.csproj". Addon state: "CompilingError". The addon either did not update or did not compile!

**Comment by Pentarina** [comment]
[compile_log_Berb.Common_B53F94EC.txt](https://github.com/Muse30/PortAIO/files/270629/compile_log_Berb.Common_B53F94EC.txt)

**Comment by Pentarina** [comment]
Help me bro ;/

**Comment by dankmemer420** [comment]
https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/#comment-159210 Have you tried this?

**Comment by Pentarina** [comment]
Yep, still same error.

**Comment by wwomegaww** [comment]
I had the same problem, but i fixed cleaning my app data and restarting eb, hope it works

**Comment by Pentarina** [comment]
I am idiot. I've restet compiuter and now working fine. Thank you guys!

**Comment by Muse30** [comment]
nice glad is working for you now
