### ISSUE TITLE
Yasuo '-'

### ISSUE THREAD

**Issue by beadwarf** [Muse30/PortAIO#38]
yasuo Q is going far away from minions ( sometimes even champs) halp me sir

**Comment by Muse30** [comment]
Valvresharp?

**Comment by beadwarf** [comment]
YE

**Comment by Muse30** [comment]
the original Valvresharp is also having a lot of problems so I will try to fix when the original is updated

probably will port another yasuo

**Comment by beadwarf** [comment]
Thx!
