### ISSUE TITLE
Lucian

### ISSUE THREAD

**Issue by DannyTheGod** [Muse30/PortAIO#40]
LCS_Lucian , Challenger Lucian , both of they dont use any spells in combo and harass, can you check it 
iLucian works fine but it doesnt use Q Extend in Harass mode like LCS Lucian and Challenger Lucian 
p/s thank for your work anyway

**Comment by lightduy94** [comment]
+1 Same

**Comment by lyn690697457** [comment]
iLucian not spells clear and Harass
