### ISSUE TITLE
Caitlyn block manual W sometimes

### ISSUE THREAD

**Issue by lightduy94** [Muse30/PortAIO#5]
First, i really thank you for continue updating this awesome project. Really really thank you!
Then is feed back about Caitlyn, OKTW Cait block manual W sometimes. Please fix it!

**Comment by Muse30** [comment]
when does this happen? I just tested and I can manually W everytime

**Comment by lightduy94** [comment]
For me i just can W 1 times then i need to wait long time to put another W manual.
Will test more anh try to figure out when this happened

**Comment by voidsurfer** [comment]
I'm pretty sure this is a humanizer issue. This happened to me on different champions when i had really low settings on ThugDogeHumanizer, it happened almost everygame when i used AntiRito (Thats why no one should ever use that one)

**Comment by lightduy94** [comment]
I don't use any Humanizer and i found that OKTW Cait only can put 1 trap and have to wait when enemy is near

**Comment by Muse30** [comment]
couldnt reproduce this error.. if someone else has please open a new issue
